services:
  soltix-web-build:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5555}
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY:-}
    image: soltix-web-build
    container_name: soltix-web-build
    entrypoint: ["sh", "-c", "cp -r /out/* /export/"]
    volumes:
      - ./out:/export
