services:
  soltix-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5555}
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY:-}
    container_name: soltix-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5555}
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY:-}
    restart: unless-stopped
